"use strict";

const SUBSCRIPTION_ATTEMPT_STATUS = Object.freeze({
  PROCESSING: "processing",
  LEGACY_PROCESSING: "criando",
  PENDING: "pending",
  AUTHORIZED: "authorized",
  APPROVED: "approved",
  CANCELLED: "cancelled",
  EXPIRED: "expired",
  FAILED: "failed",
  SUPERSEDED: "superseded",
  RECONCILIATION_REQUIRED: "reconciliation_required",
});

const BLOCKING_ATTEMPT_STATUSES = Object.freeze([
  SUBSCRIPTION_ATTEMPT_STATUS.PROCESSING,
  SUBSCRIPTION_ATTEMPT_STATUS.LEGACY_PROCESSING,
  SUBSCRIPTION_ATTEMPT_STATUS.PENDING,
  SUBSCRIPTION_ATTEMPT_STATUS.AUTHORIZED,
]);

const CANCELLABLE_ATTEMPT_STATUSES = BLOCKING_ATTEMPT_STATUSES;

module.exports = {
  BLOCKING_ATTEMPT_STATUSES,
  CANCELLABLE_ATTEMPT_STATUSES,
  SUBSCRIPTION_ATTEMPT_STATUS,
};
